version: '3'
services:
  db:
    image: postgres:11.5
    volumes:
    - ./backend/db/pgdata:/var/lib/postgresql/data
    ports:
    - 5432:5432
    restart: always

  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && rails server -p 8080 -b 0.0.0.0"
    volumes:
      - ./backend:/app/backend
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST: db
    tty: true